In [122]:
import pandas as pd

In [105]:
df=pd.read_csv('Car_sales.csv')
df

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,Acura,Integra,16.919,16.360,Passenger,21.50,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2/2/2012,58.280150
1,Acura,TL,39.384,19.875,Passenger,28.40,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,6/3/2011,91.370778
2,Acura,CL,14.114,18.225,Passenger,NaN,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,1/4/2012,NaN
3,Acura,RL,8.588,29.725,Passenger,42.00,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779
4,Audi,A4,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,10/8/2011,62.777639
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,Volvo,V40,3.545,NaN,Passenger,24.40,1.9,160.0,100.5,67.6,176.6,3.042,15.8,25.0,9/21/2011,66.498812
153,Volvo,S70,15.245,NaN,Passenger,27.50,2.4,168.0,104.9,69.3,185.9,3.208,17.9,25.0,11/24/2012,70.654495
154,Volvo,V70,17.531,NaN,Passenger,28.80,2.4,168.0,104.9,69.3,186.2,3.259,17.9,25.0,6/25/2011,71.155978
155,Volvo,C70,3.493,NaN,Passenger,45.50,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,4/26/2011,101.623357
156,Volvo,S80,18.969,NaN,Passenger,36.00,2.9,201.0,109.9,72.1,189.8,3.600,21.1,24.0,11/14/2011,85.735655

In [106]:
# selecting columns
df=df[['Manufacturer','Sales_in_thousands',
                 'Vehicle_type','Price_in_thousands',
                 'Engine_size','Horsepower','Fuel_capacity']]

In [107]:
df

,Manufacturer,Sales_in_thousands,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
0,Acura,16.919,Passenger,21.50,1.8,140.0,13.2
1,Acura,39.384,Passenger,28.40,3.2,225.0,17.2
2,Acura,14.114,Passenger,NaN,3.2,225.0,17.2
3,Acura,8.588,Passenger,42.00,3.5,210.0,18.0
4,Audi,20.397,Passenger,23.99,1.8,150.0,16.4
...,...,...,...,...,...,...,...
152,Volvo,3.545,Passenger,24.40,1.9,160.0,15.8
153,Volvo,15.245,Passenger,27.50,2.4,168.0,17.9
154,Volvo,17.531,Passenger,28.80,2.4,168.0,17.9
155,Volvo,3.493,Passenger,45.50,2.3,236.0,18.5
156,Volvo,18.969,Passenger,36.00,2.9,201.0,21.1

In [108]:
# calculate the number of unique values
df.nunique()

Manufacturer           30
Sales_in_thousands    157
Vehicle_type            2
Price_in_thousands    152
Engine_size            31
Horsepower             66
Fuel_capacity          55
dtype: int64

# agg()

In [110]:
# calculate the sum of columns
df.agg('sum')

Manufacturer          AcuraAcuraAcuraAcuraAudiAudiAudiBMWBMWBMWBuick...
Sales_in_thousands                                             8320.698
Vehicle_type          PassengerPassengerPassengerPassengerPassengerP...
Price_in_thousands                                             4245.567
Engine_size                                                       477.5
Horsepower                                                      29008.0
Fuel_capacity                                                    2800.5
dtype: object

In [111]:
#calculate the mean of numeric columnd
df.agg('mean',numeric_only=True)

Sales_in_thousands     52.998076
Price_in_thousands     27.390755
Engine_size             3.060897
Horsepower            185.948718
Fuel_capacity          17.951923
dtype: float64

In [112]:
# Different aggregations per column:calculate the sum and mean of 'Sales_in_thousands'
#and sum and max of 'Price_in_thousands'
df.agg({'Sales_in_thousands':['sum','mean'],
         'Price_in_thousands':['sum','max']})

      Sales_in_thousands  Price_in_thousands
sum          8320.698000            4245.567
mean           52.998076                 NaN
max                  NaN              85.500

In [113]:
#aggregate over the columns
df[['Sales_in_thousands','Price_in_thousands']].agg('sum',axis=1)

0      38.419
1      67.784
2      14.114
3      50.588
4      44.387
        ...
152    27.945
153    42.745
154    46.331
155    48.993
156    54.969
Length: 157, dtype: float64

In [114]:
# equivalent (NaN behaves differently)
df['Sales_in_thousands']+df['Price_in_thousands']

0      38.419
1      67.784
2         NaN
3      50.588
4      44.387
        ...
152    27.945
153    42.745
154    46.331
155    48.993
156    54.969
Length: 157, dtype: float64

In [115]:
# aggregate different functions and reaname the index of resulting dataframe
df.agg(x=('Sales_in_thousands','sum'),
       y=('Price_in_thousands','sum'))

   Sales_in_thousands  Price_in_thousands
x            8320.698                 NaN
y                 NaN            4245.567

# The Split-Apply-Combine Strategy

In [117]:
# Split data into separate groups
passenger_filter=df['Vehicle_type']=='Passenger'
car_filter=df['Vehicle_type']=='Car'
#df['Vehicle_type'].value_counts()

In [118]:
# apply an operation
passenger_avg=df[passenger_filter] ['Sales_in_thousands'].mean()
car_avg=df[car_filter]['Sales_in_thousands'].mean()

In [126]:
# combine results
pd.DataFrame({'Vehicle_type':['Car','Passenger'],
              'Sales_in_thousands':[car_avg,passenger_avg]})

  Vehicle_type  Sales_in_thousands
0          Car           80.622293
1    Passenger           43.234345

# groupby()

In [139]:
# group by Vehicle_type and calculate the mean
df.groupby('Vehicle_type').mean(numeric_only=True)

,Sales_in_thousands,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
Vehicle_type,,,,,
Car,80.622293,26.319975,3.520000,186.400000,21.895000
Passenger,43.234345,27.763200,2.902586,185.793103,16.592241

In [143]:
# group by Manufacturer
groupby_obj=df.groupby('Manufacturer')

In [145]:
groupby_obj

In [153]:
groupby_obj.groups.keys()
groupby_obj.groups

{'Acura': [0, 1, 2, 3], 'Audi': [4, 5, 6], 'BMW': [7, 8, 9], 'Buick': [10, 11, 12, 13], 'Cadillac': [14, 15, 16, 17, 18], 'Chevrolet': [19, 20, 21, 22, 23, 24, 25, 26, 27], 'Chrysler': [28, 29, 30, 31, 32, 33, 34], 'Dodge': [35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45], 'Ford': [46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56], 'Honda': [57, 58, 59, 60, 61], 'Hyundai': [62, 63, 64], 'Infiniti': [65], 'Jaguar': [66], 'Jeep': [67, 68, 69], 'Lexus': [70, 71, 72, 73, 74, 75], 'Lincoln': [76, 77, 78], 'Mercedes-B': [92, 93, 94, 95, 96, 97, 98, 99, 100], 'Mercury': [86, 87, 88, 89, 90, 91], 'Mitsubishi': [79, 80, 81, 82, 83, 84, 85], 'Nissan': [101, 102, 103, 104, 105, 106, 107], 'Oldsmobile': [108, 109, 110, 111, 112, 113], 'Plymouth': [114, 115, 116, 117], 'Pontiac': [118, 119, 120, 121, 122, 123], 'Porsche': [124, 125, 126], 'Saab': [127, 128], 'Saturn': [129, 130, 131, 132, 133], 'Subaru': [134, 135], 'Toyota': [136, 137, 138, 139, 140, 141, 142, 143, 144], 'Volkswagen': [145, 146, 147, 148, 149, 150], 'Volvo': [151, 152, 153, 154, 155, 156]}

In [151]:
# get a specific group within the Manufacturer column
groupby_obj.get_group('Ford')

,Manufacturer,Sales_in_thousands,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
46,Ford,70.227,Passenger,12.070,2.0,110.0,12.7
47,Ford,113.369,Passenger,21.560,3.8,190.0,15.7
48,Ford,35.068,Passenger,17.035,2.5,170.0,15.0
49,Ford,245.815,Passenger,17.885,3.0,155.0,16.0
50,Ford,175.670,Passenger,12.315,2.0,107.0,13.2
51,Ford,63.403,Passenger,22.195,4.6,200.0,19.0
52,Ford,276.747,Car,31.930,4.0,210.0,21.0
53,Ford,155.787,Car,21.410,3.0,150.0,26.0
54,Ford,125.338,Car,36.135,4.6,240.0,26.0
55,Ford,220.650,Car,12.050,2.5,119.0,20.0
56,Ford,540.561,Car,26.935,4.6,220.0,25.1

In [157]:
# group by Manufacturer and calculate the mean
df.groupby('Manufacturer').mean(numeric_only=True)

,Sales_in_thousands,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
Manufacturer,,,,,
Acura,19.751250,30.633333,2.925000,200.000000,16.400000
Audi,13.519000,39.980000,2.933333,220.000000,19.533333
BMW,15.501667,33.096667,2.700000,185.333333,17.233333
Buick,60.504750,26.781250,3.625000,206.250000,17.750000
Cadillac,22.435600,40.254000,4.500000,256.000000,20.800000
Chevrolet,61.596111,20.022778,3.055556,171.111111,15.477778
Chrysler,28.817286,23.430833,2.783333,194.833333,16.483333
Dodge,82.740818,24.213636,3.709091,199.545455,21.581818
Ford,183.875909,21.047273,3.327273,170.090909,19.063636
Honda,118.534800,20.277000,2.520000,160.400000,17.080000
Hyundai,45.775333,12.165667,1.966667,126.666667,14.533333
Infiniti,23.713000,29.465000,3.000000,227.000000,18.500000
Jaguar,15.467000,42.800000,3.000000,240.000000,18.400000
Jeep,97.717667,20.991667,3.500000,168.333333,19.833333
Lexus,17.807167,44.055000,3.616667,245.833333,20.533333
Lincoln,28.544667,41.690000,4.866667,263.333333,23.000000
Mercedes-B,13.013889,52.916667,3.422222,232.222222,18.922222
Mercury,39.666500,20.748333,3.150000,163.833333,17.833333
Mitsubishi,25.842143,22.167429,2.800000,165.142857,18.285714
Nissan,57.090714,22.360714,2.914286,169.000000,18.200000
Oldsmobile,29.831500,25.622833,3.450000,190.000000,18.200000
Plymouth,16.000250,22.642500,2.475000,166.750000,15.125000
Pontiac,61.755667,22.949167,3.433333,185.000000,17.916667
Porsche,4.042667,62.473333,3.166667,272.333333,17.000000
Saab,10.653000,29.610000,2.150000,177.500000,17.700000
Saturn,33.770000,14.271000,2.020000,119.600000,12.500000
Subaru,40.067500,21.395000,2.500000,165.000000,16.400000
Toyota,82.245000,21.982889,2.622222,160.666667,17.766667
Volkswagen,34.868667,17.698333,1.966667,120.833333,14.700000
Volvo,12.623333,30.933333,2.300000,182.166667,17.833333