In [1]:
import pandas as pd

In [3]:
df1=pd.DataFrame({'id':['A','B','C','D'],
                   'age':[30,23,25,22]})
df2=pd.DataFrame({'id':['C','D','E','F'],
                   'job':['Doctor','Statistician',
                        'Accountant','Developer']})

# Exclusive outer join(Exclusive Full join)

In [12]:
df1.merge(df2,on='id',how='outer')

  id   age           job
0  A  30.0           NaN
1  B  23.0           NaN
2  C  25.0        Doctor
3  D  22.0  Statistician
4  E   NaN    Accountant
5  F   NaN     Developer

In [14]:
# indicator = True 
df1.merge(df2,on='id',how='outer', indicator=True)

  id   age           job      _merge
0  A  30.0           NaN   left_only
1  B  23.0           NaN   left_only
2  C  25.0        Doctor        both
3  D  22.0  Statistician        both
4  E   NaN    Accountant  right_only
5  F   NaN     Developer  right_only

In [18]:
# query
df1.merge(df2,on='id',how='outer',
          indicator=True).query("_merge=='left_only' or _merge=='right_only'")

  id   age         job      _merge
0  A  30.0         NaN   left_only
1  B  23.0         NaN   left_only
4  E   NaN  Accountant  right_only
5  F   NaN   Developer  right_only

# Exercise

In [21]:
df_movies=pd.read_csv('IMDb movies.csv',low_memory=False)
df_ratings=pd.read_csv('IMDb ratings.csv')

In [25]:
# merge df_movies and df_ratings
df_movies.merge(df_ratings,on='imdb_title_id',how='outer',
                indicator=True)

,imdb_title_id,title,original_title,year,date_published,genre,duration,country,language,director,...,females_30age_votes,females_45age_avg_vote,females_45age_votes,top1000_voters_rating,top1000_voters_votes,us_voters_rating,us_voters_votes,non_us_voters_rating,non_us_voters_votes,_merge
0,tt0000009,Miss Jerry,Miss Jerry,1894,1894-10-09,Romance,45,USA,NaN,Alexander Black,...,13.0,4.5,4.0,5.7,34.0,6.4,51.0,6.0,70.0,both
1,tt0000574,The Story of the Kelly Gang,The Story of the Kelly Gang,1906,1906-12-26,"Biography, Crime, Drama",70,Australia,NaN,Charles Tait,...,23.0,6.6,14.0,6.4,66.0,6.0,96.0,6.2,331.0,both
2,tt0001892,Den sorte drøm,Den sorte drøm,1911,1911-08-19,Drama,53,"Germany, Denmark",NaN,Urban Gad,...,4.0,6.8,7.0,5.4,32.0,6.2,31.0,5.9,123.0,both
3,tt0002101,Cleopatra,Cleopatra,1912,1912-11-13,"Drama, History",100,USA,English,Charles L. Gaskill,...,14.0,6.1,21.0,4.9,57.0,5.5,207.0,4.7,105.0,both
4,tt0002130,L'Inferno,L'Inferno,1911,1911-03-06,"Adventure, Drama, Fantasy",68,Italy,Italian,"Francesco Bertolini, Adolfo Padovan",...,82.0,7.4,77.0,6.9,139.0,7.0,488.0,7.0,1166.0,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85850,tt9908390,Le lion,Le lion,2020,2020-01-29,Comedy,95,"France, Belgium",French,Ludovic Colbeau-Justin,...,11.0,5.0,2.0,5.5,12.0,6.3,22.0,5.3,214.0,both
85851,tt9911196,De Beentjes van Sint-Hildegard,De Beentjes van Sint-Hildegard,2020,2020-02-13,"Comedy, Drama",103,Netherlands,"German, Dutch",Johan Nijenhuis,...,47.0,7.3,30.0,7.0,6.0,6.8,13.0,7.7,388.0,both
85852,tt9911774,Padmavyuhathile Abhimanyu,Padmavyuhathile Abhimanyu,2019,2019-03-08,Drama,130,India,Malayalam,Vineesh Aaradya,...,NaN,NaN,NaN,1.0,1.0,NaN,NaN,2.0,2.0,both
85853,tt9914286,Sokagin Çocuklari,Sokagin Çocuklari,2019,2019-03-15,"Drama, Family",98,Turkey,Turkish,Ahmet Faik Akinci,...,NaN,7.0,1.0,4.0,3.0,1.7,5.0,5.8,5.0,both
85854,tt9914942,La vida sense la Sara Amat,La vida sense la Sara Amat,2019,2020-02-05,Drama,74,Spain,Catalan,Laura Jou,...,4.0,7.5,4.0,7.0,4.0,6.7,13.0,6.7,60.0,both

In [27]:
df_movies.merge(df_ratings,on='imdb_title_id',how='outer',
                indicator=True).query("_merge=='left_only' or _merge=='right_only'")

Empty DataFrame
Columns: [imdb_title_id, title, original_title, year, date_published, genre, duration, country, language, director, writer, production_company, actors, description, avg_vote, votes, budget, usa_gross_income, worlwide_gross_income, metascore, reviews_from_users, reviews_from_critics, weighted_average_vote, total_votes, mean_vote, median_vote, votes_10, votes_9, votes_8, votes_7, votes_6, votes_5, votes_4, votes_3, votes_2, votes_1, allgenders_0age_avg_vote, allgenders_0age_votes, allgenders_18age_avg_vote, allgenders_18age_votes, allgenders_30age_avg_vote, allgenders_30age_votes, allgenders_45age_avg_vote, allgenders_45age_votes, males_allages_avg_vote, males_allages_votes, males_0age_avg_vote, males_0age_votes, males_18age_avg_vote, males_18age_votes, males_30age_avg_vote, males_30age_votes, males_45age_avg_vote, males_45age_votes, females_allages_avg_vote, females_allages_votes, females_0age_avg_vote, females_0age_votes, females_18age_avg_vote, females_18age_votes, females_30age_avg_vote, females_30age_votes, females_45age_avg_vote, females_45age_votes, top1000_voters_rating, top1000_voters_votes, us_voters_rating, us_voters_votes, non_us_voters_rating, non_us_voters_votes, _merge]
Index: []

[0 rows x 71 columns]