In [1]:
import pandas as pd

In [3]:
df1=pd.DataFrame({'id':['A','B','C','D'],
                   'age':[30,23,25,22]})
df2=pd.DataFrame({'id':['C','D','E','F'],
                   'job':['Doctor','Statistician',
                        'Accountant','Developer']})

In [7]:
df1.merge(df2,on='id',how='outer',indicator=True)

  id   age           job      _merge
0  A  30.0           NaN   left_only
1  B  23.0           NaN   left_only
2  C  25.0        Doctor        both
3  D  22.0  Statistician        both
4  E   NaN    Accountant  right_only
5  F   NaN     Developer  right_only

In [11]:
#query
df1.merge(df2,on='id',how='outer',
          indicator=True).query("_merge=='left_only'")

  id   age  job     _merge
0  A  30.0  NaN  left_only
1  B  23.0  NaN  left_only

# Exercise

In [14]:
df_movies=pd.read_csv('IMDb movies.csv',low_memory=False)
df_ratings=pd.read_csv('IMDb ratings.csv')

In [20]:
# make a copy of the df_movies dataframe 
df_movies2=df_movies.copy()

In [22]:
# set the first 1000 values of 'imdb_title_id' column as 'tt1234567890'
for index in df_movies2.index:
    if index<1000:
        df_movies2.loc[index,'imdb_title_id']='tt1234567890'

In [28]:
df_movies2

,imdb_title_id,title,original_title,year,date_published,genre,duration,country,language,director,...,actors,description,avg_vote,votes,budget,usa_gross_income,worlwide_gross_income,metascore,reviews_from_users,reviews_from_critics
0,tt1234567890,Miss Jerry,Miss Jerry,1894,1894-10-09,Romance,45,USA,NaN,Alexander Black,...,"Blanche Bayliss, William Courtenay, Chauncey D...",The adventures of a female reporter in the 1890s.,5.9,154,NaN,NaN,NaN,NaN,1.0,2.0
1,tt1234567890,The Story of the Kelly Gang,The Story of the Kelly Gang,1906,1906-12-26,"Biography, Crime, Drama",70,Australia,NaN,Charles Tait,...,"Elizabeth Tait, John Tait, Norman Campbell, Be...",True story of notorious Australian outlaw Ned ...,6.1,589,$ 2250,NaN,NaN,NaN,7.0,7.0
2,tt1234567890,Den sorte drøm,Den sorte drøm,1911,1911-08-19,Drama,53,"Germany, Denmark",NaN,Urban Gad,...,"Asta Nielsen, Valdemar Psilander, Gunnar Helse...",Two men of high rank are both wooing the beaut...,5.8,188,NaN,NaN,NaN,NaN,5.0,2.0
3,tt1234567890,Cleopatra,Cleopatra,1912,1912-11-13,"Drama, History",100,USA,English,Charles L. Gaskill,...,"Helen Gardner, Pearl Sindelar, Miss Fielding, ...",The fabled queen of Egypt's affair with Roman ...,5.2,446,$ 45000,NaN,NaN,NaN,25.0,3.0
4,tt1234567890,L'Inferno,L'Inferno,1911,1911-03-06,"Adventure, Drama, Fantasy",68,Italy,Italian,"Francesco Bertolini, Adolfo Padovan",...,"Salvatore Papa, Arturo Pirovano, Giuseppe de L...",Loosely adapted from Dante's Divine Comedy and...,7.0,2237,NaN,NaN,NaN,NaN,31.0,14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85850,tt9908390,Le lion,Le lion,2020,2020-01-29,Comedy,95,"France, Belgium",French,Ludovic Colbeau-Justin,...,"Dany Boon, Philippe Katerine, Anne Serra, Samu...",A psychiatric hospital patient pretends to be ...,5.3,398,NaN,NaN,$ 3507171,NaN,NaN,4.0
85851,tt9911196,De Beentjes van Sint-Hildegard,De Beentjes van Sint-Hildegard,2020,2020-02-13,"Comedy, Drama",103,Netherlands,"German, Dutch",Johan Nijenhuis,...,"Herman Finkers, Johanna ter Steege, Leonie ter...",A middle-aged veterinary surgeon believes his ...,7.7,724,NaN,NaN,$ 7299062,NaN,6.0,4.0
85852,tt9911774,Padmavyuhathile Abhimanyu,Padmavyuhathile Abhimanyu,2019,2019-03-08,Drama,130,India,Malayalam,Vineesh Aaradya,...,"Anoop Chandran, Indrans, Sona Nair, Simon Brit...",NaN,7.9,265,NaN,NaN,NaN,NaN,NaN,NaN
85853,tt9914286,Sokagin Çocuklari,Sokagin Çocuklari,2019,2019-03-15,"Drama, Family",98,Turkey,Turkish,Ahmet Faik Akinci,...,"Ahmet Faik Akinci, Belma Mamati, Metin Keçeci,...",NaN,6.4,194,NaN,NaN,$ 2833,NaN,NaN,NaN
85854,tt9914942,La vida sense la Sara Amat,La vida sense la Sara Amat,2019,2020-02-05,Drama,74,Spain,Catalan,Laura Jou,...,"Maria Morera Colomer, Biel Rossell Pelfort, Is...","Pep, a 13-year-old boy, is in love with a girl...",6.7,102,NaN,NaN,$ 59794,NaN,NaN,2.0

In [32]:
# merge df_movies and df_ratings(exclusive left join)
df_exc_left=df_movies2.merge(df_ratings, on='imdb_title_id',how='outer',
                indicator=True).query("_merge=='left_only'")

In [40]:
print(df_exc_left.shape)
print(df_movies2.shape)
print(df_ratings.shape)

(1000, 71)
(85855, 22)
(85855, 49)