In [1]:
import pandas as pd

In [3]:
df1=pd.DataFrame({'id':['A','B','C','D'],
                   'age':[30,23,25,22]})
df2=pd.DataFrame({'id':['C','D','E','F'],
                   'job':['Doctor','Statistician',
                        'Accountant','Developer']})

In [7]:
df1.merge(df2,on='id',how='outer', indicator=True)

  id   age           job      _merge
0  A  30.0           NaN   left_only
1  B  23.0           NaN   left_only
2  C  25.0        Doctor        both
3  D  22.0  Statistician        both
4  E   NaN    Accountant  right_only
5  F   NaN     Developer  right_only

In [11]:
df1.merge(df2,on='id',how='right', 
          indicator=True).query(" _merge=='right_only'")

  id  age         job      _merge
2  E  NaN  Accountant  right_only
3  F  NaN   Developer  right_only

# Exercise

In [14]:
df_movies=pd.read_csv('IMDb movies.csv',low_memory=False)
df_ratings=pd.read_csv('IMDb ratings.csv')

In [16]:
# make a copy of the df_ratings dataframe 
df_rating_copy=df_ratings.copy()

In [22]:
# set the first 100 values if 'imdb_title_id' column as 'tt1234567890'
for index in df_rating_copy.index:
     if index<1000:
         df_rating_copy.loc[index,'imdb_title_id']='tt1234567890'

In [24]:
df_rating_copy

,imdb_title_id,weighted_average_vote,total_votes,mean_vote,median_vote,votes_10,votes_9,votes_8,votes_7,votes_6,...,females_30age_avg_vote,females_30age_votes,females_45age_avg_vote,females_45age_votes,top1000_voters_rating,top1000_voters_votes,us_voters_rating,us_voters_votes,non_us_voters_rating,non_us_voters_votes
0,tt1234567890,5.9,154,5.9,6.0,12,4,10,43,28,...,5.7,13.0,4.5,4.0,5.7,34.0,6.4,51.0,6.0,70.0
1,tt1234567890,6.1,589,6.3,6.0,57,18,58,137,139,...,6.2,23.0,6.6,14.0,6.4,66.0,6.0,96.0,6.2,331.0
2,tt1234567890,5.8,188,6.0,6.0,6,6,17,44,52,...,5.8,4.0,6.8,7.0,5.4,32.0,6.2,31.0,5.9,123.0
3,tt1234567890,5.2,446,5.3,5.0,15,8,16,62,98,...,5.5,14.0,6.1,21.0,4.9,57.0,5.5,207.0,4.7,105.0
4,tt1234567890,7.0,2237,6.9,7.0,210,225,436,641,344,...,7.3,82.0,7.4,77.0,6.9,139.0,7.0,488.0,7.0,1166.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85850,tt9908390,5.3,398,5.5,6.0,13,9,26,65,104,...,5.7,11.0,5.0,2.0,5.5,12.0,6.3,22.0,5.3,214.0
85851,tt9911196,7.7,724,7.9,8.0,65,139,288,170,42,...,8.0,47.0,7.3,30.0,7.0,6.0,6.8,13.0,7.7,388.0
85852,tt9911774,7.9,265,7.8,8.0,63,29,61,61,31,...,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,2.0,2.0
85853,tt9914286,6.4,194,9.4,10.0,176,0,2,2,1,...,NaN,NaN,7.0,1.0,4.0,3.0,1.7,5.0,5.8,5.0
85854,tt9914942,6.7,102,6.8,7.0,4,4,21,35,27,...,6.8,4.0,7.5,4.0,7.0,4.0,6.7,13.0,6.7,60.0

In [32]:
# merge df_movies and df_rating_copy
right_only=df_movies.merge( df_rating_copy,on='imdb_title_id',how='outer',
               indicator=True).query("_merge=='right_only'")

In [36]:
# shape
print(df_movies.shape)
print(df_rating_copy.shape)
print(right_only.shape)

(85855, 22)
(85855, 49)
(1000, 71)