In [1]:
import pandas as pd

In [11]:
df=pd.read_csv('players_20.csv')
#Set index
df.set_index('short_name',inplace=True)
#select column
df=df[['long_name',	'age', 'dob',	'height_cm',	'weight_kg',	'nationality', 'club']]

# Sample()

In [24]:
# extract 10 random elements from the "nationality" column
df['nationality'].sample(10,random_state=99)

short_name
R. Alvarado               Mexico
Qiao Wei                China PR
E. Paredes                 Chile
K. Stoyanov             Bulgaria
M. Chudý                Slovakia
D. Sundaram                India
R. Gagliardini             Italy
G. Debeljuh              Croatia
Kim Seung Yong    Korea Republic
M. Hansen                Denmark
Name: nationality, dtype: object

In [63]:
# extract a random 20% sample of dataframe 
df.sample(frac=0.2,random_state=1)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
D. Cvetinović,Dušan Cvetinović,30,1988-12-24,186,79,Serbia,Yokohama F. Marinos
M. Silva,Marcelo Silva,30,1989-03-21,185,82,Uruguay,Real Salt Lake
S. Mandash,Sultan Ahmed Mandash,24,1994-10-17,167,63,Saudi Arabia,Al Ahli
I. Gruev,Ilia Gruev,19,2000-05-06,189,74,Bulgaria,SV Werder Bremen
Kangin Lee,이강인 Kangin Lee,18,2001-02-19,173,61,Korea Republic,Valencia CF
...,...,...,...,...,...,...,...
P. Finger,Patrick Finger,18,2001-01-01,166,61,Germany,Eintracht Frankfurt
T. Băluță,Tudor Băluță,20,1999-03-27,191,80,Romania,Brighton & Hove Albion
Adrián Maideira,Adrián Guto Maideira Almeida,35,1984-02-29,170,66,Brazil,Goiás
Choi Chul Soon,최철순 崔喆淳,32,1987-02-08,175,68,Korea Republic,Jeonbuk Hyundai Motors
K. Agard,Kieran Agard,29,1989-10-10,176,67,England,Milton Keynes Dons

In [67]:
# unsample: increase the sampling rate-> frac>1(note:replace parameter has to be true for frac parameter > 1)
df.sample(frac=2,replace=True)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
J. Rodon,Joe Rodon,21,1997-10-22,193,76,Wales,Swansea City
Ismaily,Ismaily Gonçalves dos S.,29,1990-01-11,177,78,Brazil,Shakhtar Donetsk
C. Pain,Connor Pain,25,1993-11-11,175,68,Australia,Western United FC
Felipe Saad,Felipe Patavino Saad,35,1983-09-11,187,83,Brazil,Paris FC
J. Hesketh,Jake Hesketh,23,1996-03-27,168,63,England,Southampton
...,...,...,...,...,...,...,...
Q. Moll,Quirin Moll,28,1991-01-21,182,77,Germany,TSV 1860 München
Y. Nakayama,中山 雄太,22,1997-02-16,181,76,Japan,PEC Zwolle
R. Quioto,Romell Quioto,27,1991-08-09,180,78,Honduras,Houston Dynamo
S. Kalu,Samuel Kalu Ojim,21,1997-08-26,176,74,Nigeria,FC Girondins de Bordeaux
Sillero,Jon Sillero Monreal,21,1998-05-24,176,79,Spain,Athletic Club de Bilbao